/**
 * Inspired by the Power CAT Copilot Studio Kit
 * (https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit)
 * Ported to run locally without Power Platform/Dataverse dependencies.
 * Original kit is maintained by the Power Customer Advisory Team at Microsoft.
 */
import { defaultStyleOptions } from "../style-options";
import type { WebChatTheme } from "../types";

function createTheme(
  id: string,
  name: string,
  description: string,
  styleOptions: WebChatTheme["styleOptions"],
): WebChatTheme {
  return {
    id,
    name,
    description,
    styleOptions: {
      ...defaultStyleOptions,
      ...styleOptions,
    },
  };
}

export const themes: WebChatTheme[] = [
  createTheme(
    "default-blue",
    "Default Blue",
    "Microsoft-style blue accent with a clean light-gray chat surface.",
    {
      accent: "#0078D4",
      backgroundColor: "#F5F7FB",
      botAvatarBackgroundColor: "#0078D4",
      botAvatarInitials: "AI",
      bubbleBackground: "#FFFFFF",
      bubbleBorderRadius: 18,
      bubbleBorderColor: "#D7E0EA",
      bubbleTextColor: "#0F172A",
      bubbleFromUserBackground: "#0078D4",
      bubbleFromUserBorderRadius: 18,
      bubbleFromUserTextColor: "#FFFFFF",
      sendBoxBackground: "#FFFFFF",
      sendBoxBorderTop: "1px solid #D7E0EA",
      sendBoxButtonColor: "#0078D4",
      sendBoxHeight: 52,
      suggestedActionBackgroundColor: "#FFFFFF",
      suggestedActionTextColor: "#005EA6",
      suggestedActionBorderRadius: 999,
      avatarSize: 36,
      paddingRegular: 12,
    },
  ),
  createTheme(
    "dark-mode",
    "Dark Mode",
    "Dark surfaces with a Copilot-style blue accent and bright readable chat bubbles.",
    {
      accent: "#4CC2FF",
      backgroundColor: "#1E1E1E",
      botAvatarBackgroundColor: "#0078D4",
      botAvatarInitials: "AI",
      bubbleBackground: "#2A2A2A",
      bubbleBorderRadius: 18,
      bubbleBorderColor: "#3F3F46",
      bubbleTextColor: "#F5F5F5",
      bubbleFromUserBackground: "#0078D4",
      bubbleFromUserBorderRadius: 18,
      bubbleFromUserTextColor: "#FFFFFF",
      sendBoxBackground: "#252526",
      sendBoxBorderTop: "1px solid #3F3F46",
      sendBoxButtonColor: "#4CC2FF",
      sendBoxHeight: 54,
      suggestedActionBackgroundColor: "#2D3E50",
      suggestedActionTextColor: "#F5F5F5",
      suggestedActionBorderRadius: 999,
      avatarSize: 36,
      paddingRegular: 12,
      sendBoxTextColor: "#F5F5F5",
      sendBoxPlaceholderColor: "#A1A1AA",
      bubbleFromUserBorderColor: "#0078D4",
      suggestedActionBorderColor: "#3F3F46",
      suggestedActionBackground: "#2D3E50",
      notificationText: "#E5E7EB",
    },
  ),
  createTheme(
    "warm-coral",
    "Warm Coral",
    "Friendly coral accents with softer corners and inviting backgrounds.",
    {
      accent: "#FF6B6B",
      backgroundColor: "#FFF7F5",
      botAvatarBackgroundColor: "#FF6B6B",
      botAvatarInitials: "AI",
      bubbleBackground: "#FFFFFF",
      bubbleBorderRadius: 22,
      bubbleBorderColor: "#FFD6D1",
      bubbleTextColor: "#5B3A35",
      bubbleFromUserBackground: "#FF6B6B",
      bubbleFromUserBorderRadius: 22,
      bubbleFromUserTextColor: "#FFFFFF",
      sendBoxBackground: "#FFFFFF",
      sendBoxBorderTop: "1px solid #FFD6D1",
      sendBoxButtonColor: "#FF6B6B",
      sendBoxHeight: 56,
      suggestedActionBackgroundColor: "#FFE7E2",
      suggestedActionTextColor: "#B94B4B",
      suggestedActionBorderRadius: 20,
      avatarSize: 38,
      paddingRegular: 14,
      suggestedActionBackground: "#FFE7E2",
      suggestedActionBorderColor: "#FFC4BC",
      bubbleFromUserBorderColor: "#FF6B6B",
    },
  ),
  createTheme(
    "forest-green",
    "Forest Green",
    "Nature-inspired greens and earthy neutrals for a calm conversational feel.",
    {
      accent: "#2D6A4F",
      backgroundColor: "#F3F7F2",
      botAvatarBackgroundColor: "#2D6A4F",
      botAvatarInitials: "AI",
      bubbleBackground: "#FFFFFF",
      bubbleBorderRadius: 18,
      bubbleBorderColor: "#CFE3D8",
      bubbleTextColor: "#1F392D",
      bubbleFromUserBackground: "#40916C",
      bubbleFromUserBorderRadius: 18,
      bubbleFromUserTextColor: "#FFFFFF",
      sendBoxBackground: "#FFFFFF",
      sendBoxBorderTop: "1px solid #CFE3D8",
      sendBoxButtonColor: "#2D6A4F",
      sendBoxHeight: 54,
      suggestedActionBackgroundColor: "#DCEFE5",
      suggestedActionTextColor: "#2D6A4F",
      suggestedActionBorderRadius: 18,
      avatarSize: 36,
      paddingRegular: 12,
      suggestedActionBackground: "#DCEFE5",
      suggestedActionBorderColor: "#B9D8C8",
      bubbleFromUserBorderColor: "#40916C",
    },
  ),
  createTheme(
    "purple-glow",
    "Purple Glow",
    "Modern purple styling with gradient-friendly highlights and polished surfaces.",
    {
      accent: "#742774",
      backgroundColor: "#F9F5FB",
      botAvatarBackgroundColor: "#742774",
      botAvatarInitials: "AI",
      bubbleBackground: "#FFFFFF",
      bubbleBorderRadius: 20,
      bubbleBorderColor: "#E3D4EB",
      bubbleTextColor: "#3D2248",
      bubbleFromUserBackground: "#742774",
      bubbleFromUserBorderRadius: 20,
      bubbleFromUserTextColor: "#FFFFFF",
      sendBoxBackground: "#FFFFFF",
      sendBoxBorderTop: "1px solid #E3D4EB",
      sendBoxButtonColor: "#742774",
      sendBoxHeight: 56,
      suggestedActionBackgroundColor: "#EFE2F4",
      suggestedActionTextColor: "#742774",
      suggestedActionBorderRadius: 20,
      avatarSize: 38,
      paddingRegular: 14,
      suggestedActionBackground: "#EFE2F4",
      suggestedActionBorderColor: "#D9BFE7",
      bubbleFromUserBorderColor: "#742774",
    },
  ),
];

export const defaultTheme: WebChatTheme = themes[0];
export const presetThemes: WebChatTheme[] = themes;

export function getThemeById(id: string): WebChatTheme | undefined {
  return themes.find(theme => theme.id === id);
}
